-- 바인애플 (Tiny Second-hand Marketplace) — Supabase / PostgreSQL schema
-- Apply this in: Supabase Dashboard -> SQL Editor -> New query -> Run.
-- (You normally do NOT need this: `python app.py` creates these tables
--  automatically on first start once DATABASE_URL is configured.)
--
-- Notes:
--   * "user" is quoted because it is a reserved word in PostgreSQL.
--   * dm/notification carry a monotonic identity column `seq`, used as the
--     insertion-order tie-breaker that replaces SQLite's implicit rowid.

CREATE TABLE IF NOT EXISTS "user" (
    id             text PRIMARY KEY,
    username       text UNIQUE NOT NULL,
    password_hash  text NOT NULL,
    bio            text NOT NULL DEFAULT '',
    bank_name      text NOT NULL DEFAULT '',
    account_number text NOT NULL DEFAULT '',
    account_holder text NOT NULL DEFAULT '',
    is_admin       integer NOT NULL DEFAULT 0,
    status         text NOT NULL DEFAULT 'active',
    created_at     text NOT NULL
);

CREATE TABLE IF NOT EXISTS product (
    id          text PRIMARY KEY,
    title       text NOT NULL,
    description text NOT NULL,
    price       integer NOT NULL CHECK (price >= 0),
    seller_id   text NOT NULL,
    image_path  text,
    status      text NOT NULL DEFAULT 'active',
    sale_status text NOT NULL DEFAULT 'selling',
    category    text NOT NULL DEFAULT '기타',
    created_at  text NOT NULL,
    FOREIGN KEY (seller_id) REFERENCES "user"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS favorite (
    user_id    text NOT NULL,
    product_id text NOT NULL,
    created_at text NOT NULL,
    PRIMARY KEY (user_id, product_id),
    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS report (
    id          text PRIMARY KEY,
    reporter_id text NOT NULL,
    target_type text NOT NULL,
    target_id   text NOT NULL,
    reason      text NOT NULL,
    created_at  text NOT NULL,
    UNIQUE (reporter_id, target_type, target_id),
    FOREIGN KEY (reporter_id) REFERENCES "user"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dm (
    id          text PRIMARY KEY,
    sender_id   text NOT NULL,
    receiver_id text NOT NULL,
    content     text NOT NULL,
    created_at  text NOT NULL,
    seq         bigint GENERATED BY DEFAULT AS IDENTITY,
    FOREIGN KEY (sender_id) REFERENCES "user"(id) ON DELETE CASCADE,
    FOREIGN KEY (receiver_id) REFERENCES "user"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notification (
    id         text PRIMARY KEY,
    user_id    text NOT NULL,
    type       text NOT NULL,
    actor_id   text NOT NULL,
    product_id text,
    content    text NOT NULL,
    is_read    integer NOT NULL DEFAULT 0,
    created_at text NOT NULL,
    seq        bigint GENERATED BY DEFAULT AS IDENTITY,
    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    FOREIGN KEY (actor_id) REFERENCES "user"(id) ON DELETE CASCADE
);

-- Idempotent column back-fills (safe on fresh or existing tables):
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS bank_name text NOT NULL DEFAULT '';
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS account_number text NOT NULL DEFAULT '';
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS account_holder text NOT NULL DEFAULT '';
ALTER TABLE product ADD COLUMN IF NOT EXISTS sale_status text NOT NULL DEFAULT 'selling';
ALTER TABLE product ADD COLUMN IF NOT EXISTS category text NOT NULL DEFAULT '기타';
